### ISSUE TITLE
merge current branch into master

### ISSUE THREAD

**Issue by wsh32** [nerdherd/PowerUp2018#17]
im not sure which branch is the most current but can we get that one merged into master? i always find myself referencing things we did last season and a bunch of the commands are still just skeleton

**Comment by DylanB5402** [comment]
Wesley, this repo is out of date (and a bit of a mess). We moved everything into the PowerUp2018-v2 repo when we moved over to VSCode.

**Comment by wsh32** [comment]
Gotcha. Thanks for clarifying. Can you please clean up the v2 repo (add a readme and such) and pin it to the nerdherd page?

**Comment by DylanB5402** [comment]
Yeah, sure. We'll take care of it after we're able to push code from Beach Blitz.
